version: '3'

services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - redis
      - mongo
    networks:
      - backend

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - backend

  redis:
    image: redis/redis-stack:7.4.0-rc1
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - backend

networks:
  backend: